ALTER TABLE orders ADD COLUMN payment_status VARCHAR(50) NOT NULL DEFAULT 'UNPAID';
ALTER TABLE orders ADD COLUMN platform_fee DECIMAL(19, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN net_payout DECIMAL(19, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN payment_method VARCHAR(100);
ALTER TABLE orders ADD COLUMN transaction_id VARCHAR(255);
ALTER TABLE orders ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_orders_payment_status ON orders (payment_status);